#!/usr/bin/env bash

open_in_term() {
	$TERMINAL --hold -e $@
}

[ -z "$1" ] && exit 1

if echo "${1}" | grep -Eq "^(https?://|www.)" ; then
    $BROWSER --new-tab "$1" &
    exit
fi


open_in_term $FILEMANAGER $1

